[package]
name = "gameoflife"
version = "0.1.0"
authors = ["Franck Royer <franck@royer.one>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"

[dev-dependencies]
proptest = "0.10"
